repos:
  # General file checks - SAFE
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
        args: ['--maxkb=1000']
      - id: check-json
      - id: check-merge-conflict
      - id: mixed-line-ending
        args: ['--fix=lf']

  # Python formatting only - SAFE
  - repo: https://github.com/psf/black
    rev: 24.3.0
    hooks:
      - id: black
        language_version: python3
        files: ^python-service/

  # Python linting only (no auto-fix) - SAFE
  - repo: https://github.com/pycqa/flake8
    rev: 7.0.0
    hooks:
      - id: flake8
        args: [
          '--max-line-length=120',
          '--ignore=E203,W503,E501,E402,F841,E712,F821,E741,F811',
          '--exclude=migrations,venv,__pycache__'
        ]
        files: ^python-service/

  # JavaScript/Vue linting only (no auto-fix)
  # - repo: local
  #   hooks:
  #     - id: eslint-check
  #       name: ESLint Check Only
  #       entry: bash -c 'cd rails-app && npx eslint'
  #       language: system
  #       files: \.(js|vue|ts)$
  #       types: [file]
  #       pass_filenames: true

  # Ruby linting only (no auto-fix)
  # - repo: local
  #   hooks:
  #     - id: rubocop-check
  #       name: Rubocop Check Only
  #       entry: bash -c 'cd rails-app && bundle exec rubocop'
  #       language: system
  #       files: \.rb$
  #       types: [file]
  #       pass_filenames: true