[phases.setup]
nixPkgs = ["nodejs-20_x", "postgresql_15"]
aptPkgs = ["postgresql-15-pgvector", "tesseract-ocr", "tesseract-ocr-kor"]

[phases.install]
cmds = [
  "cd rails-app",
  "gem install bundler",
  "bundle config set --local deployment 'true'",
  "bundle config set --local without 'development test'",
  "bundle install",
  "npm ci --production=false"
]

[phases.build]
cmds = [
  "cd rails-app",
  "bundle exec rails db:migrate",
  "bundle exec rails assets:precompile"
]

[start]
cmd = "cd rails-app && bundle exec puma -C config/puma.rb"

[variables]
RAILS_ENV = "production"
RAILS_LOG_TO_STDOUT = "true"
RAILS_SERVE_STATIC_FILES = "true"
NODE_ENV = "production"