# This is a template file. Create actual secrets with:
# kubectl create secret generic excel-unified-secrets \
#   --from-literal=db-password=YOUR_DB_PASSWORD \
#   --from-literal=redis-password=YOUR_REDIS_PASSWORD \
#   --from-literal=openai-api-key=YOUR_OPENAI_API_KEY \
#   --from-literal=secret-key=YOUR_SECRET_KEY \
#   --from-literal=secret-key-base=YOUR_SECRET_KEY_BASE \
#   --from-literal=grafana-user=admin \
#   --from-literal=grafana-password=YOUR_GRAFANA_PASSWORD \
#   -n excel-unified

apiVersion: v1
kind: Secret
metadata:
  name: excel-unified-secrets
  namespace: excel-unified
type: Opaque
stringData:
  db-password: "CHANGE_ME"
  redis-password: "CHANGE_ME"
  openai-api-key: "CHANGE_ME"
  secret-key: "CHANGE_ME"
  secret-key-base: "CHANGE_ME"
  grafana-user: "admin"
  grafana-password: "CHANGE_ME"